Rpf 152/biconomy middleware
rarible/ethereum-sdk pull request #100
Opened 2022-01-20 09:23 UTC by rzcoder

2022-01-23 04:22 UTC, evgenynacu commented
Will common folder be build correctly? It's outside of the package folders (don't know really, it's a question)

2022-01-23 04:23 UTC, evgenynacu requested changes

2022-01-23 04:23 UTC, evgenynacu commented on packages/biconomy-middleware/src/middleware.ts
> +import Web3 from "web3"
Web3 is a higher-level lib. let's try to avoid using it here + you don't have dependency on it in package.json

biconomy itself uses ethers (it has dependency on it. so it's better to use ethers here instead of web3)

2022-01-23 04:23 UTC, evgenynacu commented on packages/biconomy-middleware/src/middleware.ts
> +		await biconomyState
need to await for this only if biconomy should be used for sending tx, not for every request

2022-01-23 04:23 UTC, evgenynacu commented on packages/biconomy-middleware/src/types.ts
> +	abi: [
why do we need contract abi here in metadata? It should not be included here. there are 2 functions used: getNonce + executeMetaTransaction. You can include abi for them in the source code

2022-01-23 04:23 UTC, evgenynacu commented on packages/biconomy-middleware/src/types.ts
> +export interface IContractRegistry {
We need reference implementation of the registry (which load json file from the remote url)

2022-01-23 04:23 UTC, evgenynacu commented on packages/biconomy-middleware/src/tests/metaTxContract/contract.ts
> +export const rinkebyMetaTxContract = {
will this file be included in the build? It should not be, used in test only

2022-01-24 17:05 UTC, rzcoder commented on packages/biconomy-middleware/src/tests/metaTxContract/contract.ts
> +export const rinkebyMetaTxContract = {
won't, tests dir is excluded

2022-01-25 07:53 UTC, evgenynacu requested changes

2022-01-25 07:53 UTC, evgenynacu commented on packages/biconomy-middleware/README.md
> +    const walletAddress = ... // ethereum wallet
this is not used in the example. needed?

2022-01-25 07:53 UTC, evgenynacu commented on packages/biconomy-middleware/package.json
> +    "ethers": "~5.4.4"
do we need this dep? if it's already in mexa?

2022-01-25 08:30 UTC, merged